"""Fix users table schema

Revision ID: dccdf476c3dd
Revises: f2a3b4c5d6e7
Create Date: 2026-10-05 11:44:46.781208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dccdf476c3dd'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession_main_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('token_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.String(), server_default='{}', nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('token_wallet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession_sub_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['main_category_id'], ['profession_main_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profession_sub_categories_main_category_id'), 'profession_sub_categories', ['main_category_id'], unique=False)
    op.create_table('professions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('main_category_id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('riasec_code_id', sa.Integer(), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('riasec_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['main_category_id'], ['profession_main_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['riasec_code_id'], ['riasec_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['profession_sub_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_professions_main_category_id'), 'professions', ['main_category_id'], unique=False)
    op.create_index(op.f('ix_professions_riasec_code_id'), 'professions', ['riasec_code_id'], unique=False)
    op.create_index(op.f('ix_professions_sub_category_id'), 'professions', ['sub_category_id'], unique=False)
    op.create_table('profession_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profession_activities_profession_id'), 'profession_activities', ['profession_id'], unique=False)
    op.create_table('profession_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession_career_paths',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profession_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('experience_range', sa.String(length=50), nullable=False),
    sa.Column('salary_min', sa.BigInteger(), nullable=True),
    sa.Column('salary_max', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profession_career_paths_profession_id'), 'profession_career_paths', ['profession_id'], unique=False)
    op.create_table('profession_market_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession_skill_rels',
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profession_id', 'skill_id')
    )
    op.create_index(op.f('ix_profession_skill_rels_profession_id'), 'profession_skill_rels', ['profession_id'], unique=False)
    op.create_index(op.f('ix_profession_skill_rels_skill_id'), 'profession_skill_rels', ['skill_id'], unique=False)
    op.create_table('profession_tool_rels',
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profession_id', 'tool_id')
    )
    op.create_index(op.f('ix_profession_tool_rels_profession_id'), 'profession_tool_rels', ['profession_id'], unique=False)
    op.create_index(op.f('ix_profession_tool_rels_tool_id'), 'profession_tool_rels', ['tool_id'], unique=False)
    op.drop_index(op.f('ix_digital_professions_riasec_code_id'), table_name='digital_professions')
    op.drop_index(op.f('ix_digital_professions_title'), table_name='digital_professions')
    op.drop_table('digital_professions')
    op.add_column('career_recommendations', sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('career_recommendations', 'test_goal')
    op.drop_column('career_recommendations', 'created_at')
    op.alter_column('fit_check_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_fit_check_results_session'), table_name='fit_check_results')
    op.create_unique_constraint(None, 'fit_check_results', ['test_session_id'])
    op.add_column('ikigai_candidate_professions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('ikigai_candidate_professions', 'total_candidates',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_ikigai_candidates_session'), table_name='ikigai_candidate_professions')
    op.drop_column('ikigai_candidate_professions', 'generated_at')
    op.drop_column('ikigai_candidate_professions', 'max_candidates_limit')
    op.alter_column('ikigai_dimension_scores', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ikigai_dimension_scores_test_session_id'), table_name='ikigai_dimension_scores')
    op.add_column('ikigai_responses', sa.Column('dimension1_love', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ikigai_responses', sa.Column('dimension2_good_at', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ikigai_responses', sa.Column('dimension3_world_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ikigai_responses', sa.Column('dimension4_paid_for', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('ikigai_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ikigai_responses_test_session_id'), table_name='ikigai_responses')
    op.drop_column('ikigai_responses', 'dimension_2_good_at')
    op.drop_column('ikigai_responses', 'dimension_4_paid_for')
    op.drop_column('ikigai_responses', 'dimension_3_world_needs')
    op.drop_column('ikigai_responses', 'dimension_1_love')
    op.add_column('ikigai_total_scores', sa.Column('top_profession1_id', sa.BigInteger(), nullable=True))
    op.add_column('ikigai_total_scores', sa.Column('top_profession2_id', sa.BigInteger(), nullable=True))
    op.alter_column('ikigai_total_scores', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ikigai_total_scores_test_session_id'), table_name='ikigai_total_scores')
    op.drop_column('ikigai_total_scores', 'top_profession_2_id')
    op.drop_column('ikigai_total_scores', 'top_profession_1_id')
    op.drop_column('riasec_results', 'riasec_code')
    op.drop_column('riasec_results', 'scores_data')
    op.add_column('users', sa.Column('fullname', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('profile_image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('role', sa.Text(), server_default=sa.text("'USER'"), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'password')
    op.drop_column('users', 'fullname')
    op.add_column('riasec_results', sa.Column('scores_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('riasec_results', sa.Column('riasec_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('ikigai_total_scores', sa.Column('top_profession_1_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ikigai_total_scores', sa.Column('top_profession_2_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_ikigai_total_scores_test_session_id'), 'ikigai_total_scores', ['test_session_id'], unique=False)
    op.alter_column('ikigai_total_scores', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('ikigai_total_scores', 'top_profession2_id')
    op.drop_column('ikigai_total_scores', 'top_profession1_id')
    op.add_column('ikigai_responses', sa.Column('dimension_1_love', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ikigai_responses', sa.Column('dimension_3_world_needs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ikigai_responses', sa.Column('dimension_4_paid_for', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ikigai_responses', sa.Column('dimension_2_good_at', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_ikigai_responses_test_session_id'), 'ikigai_responses', ['test_session_id'], unique=False)
    op.alter_column('ikigai_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('ikigai_responses', 'dimension4_paid_for')
    op.drop_column('ikigai_responses', 'dimension3_world_needs')
    op.drop_column('ikigai_responses', 'dimension2_good_at')
    op.drop_column('ikigai_responses', 'dimension1_love')
    op.create_index(op.f('ix_ikigai_dimension_scores_test_session_id'), 'ikigai_dimension_scores', ['test_session_id'], unique=False)
    op.alter_column('ikigai_dimension_scores', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('ikigai_candidate_professions', sa.Column('max_candidates_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ikigai_candidate_professions', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_ikigai_candidates_session'), 'ikigai_candidate_professions', ['test_session_id'], unique=False)
    op.alter_column('ikigai_candidate_professions', 'total_candidates',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('ikigai_candidate_professions', 'created_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'fit_check_results', type_='unique')
    op.create_index(op.f('idx_fit_check_results_session'), 'fit_check_results', ['test_session_id'], unique=True)
    op.alter_column('fit_check_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('career_recommendations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('career_recommendations', sa.Column('test_goal', sa.VARCHAR(length=50), server_default=sa.text("'RECOMMENDATION'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('career_recommendations', 'generated_at')
    op.create_table('digital_professions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riasec_code_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['riasec_code_id'], ['riasec_codes.id'], name=op.f('digital_professions_riasec_code_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('digital_professions_pkey'))
    )
    op.create_index(op.f('ix_digital_professions_title'), 'digital_professions', ['title'], unique=True)
    op.create_index(op.f('ix_digital_professions_riasec_code_id'), 'digital_professions', ['riasec_code_id'], unique=False)
    op.drop_index(op.f('ix_profession_tool_rels_tool_id'), table_name='profession_tool_rels')
    op.drop_index(op.f('ix_profession_tool_rels_profession_id'), table_name='profession_tool_rels')
    op.drop_table('profession_tool_rels')
    op.drop_index(op.f('ix_profession_skill_rels_skill_id'), table_name='profession_skill_rels')
    op.drop_index(op.f('ix_profession_skill_rels_profession_id'), table_name='profession_skill_rels')
    op.drop_table('profession_skill_rels')
    op.drop_table('profession_market_insights')
    op.drop_index(op.f('ix_profession_career_paths_profession_id'), table_name='profession_career_paths')
    op.drop_table('profession_career_paths')
    op.drop_table('profession_aliases')
    op.drop_index(op.f('ix_profession_activities_profession_id'), table_name='profession_activities')
    op.drop_table('profession_activities')
    op.drop_index(op.f('ix_professions_sub_category_id'), table_name='professions')
    op.drop_index(op.f('ix_professions_riasec_code_id'), table_name='professions')
    op.drop_index(op.f('ix_professions_main_category_id'), table_name='professions')
    op.drop_table('professions')
    op.drop_index(op.f('ix_profession_sub_categories_main_category_id'), table_name='profession_sub_categories')
    op.drop_table('profession_sub_categories')
    op.drop_table('tools')
    op.drop_table('skills')
    op.drop_table('token_wallet', schema='public')
    op.drop_table('token_ledger', schema='public')
    op.drop_table('profession_main_categories')
    # ### end Alembic commands ###
